# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource

        druid:
            # 主库数据源
            master:
                url: jdbc:mysql://localhost:3306/headhunter?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: root
                #password: risfond@#QXK123
                password: root
                driverClassName: com.mysql.cj.jdbc.Driver
            # 测试SqlServer数据源
            slave:
                 enabled: true
                 driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
                 username: headhunter
                 password: headhunterdev
                 url: jdbc:sqlserver://192.168.30.10;DatabaseName=headhunter_0617;trustServerCertificate=true;
                 type: com.zaxxer.hikari.HikariDataSource
            #线上SqlServer数据源
#            slave:
#                 enabled: true
#                 driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#                 username: headhunterapp
#                 password: VyAsiTn3tT9Kaire2Cei
#                 url: jdbc:sqlserver://rm-2zeg45l01ape93zl5.sqlserver.rds.aliyuncs.com:3433;DatabaseName=HeadHunter;trustServerCertificate=true;
#                 type: com.zaxxer.hikari.HikariDataSource
#            slave:
#                # 从数据源开关/默认关闭
#                enabled: false
#                url:
#                username:
#                password:
            # 初始连接数
            initialSize: 5
            # 最小连接池数量
            minIdle: 10
            # 最大连接池数量
            maxActive: 20
            # 配置获取连接等待超时的时间
            maxWait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 配置一个连接在池中最大生存的时间，单位是毫秒
            maxEvictableIdleTimeMillis: 900000
            # 配置检测连接是否有效
            validationQuery: SELECT 1
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter: 
                enabled: true
            statViewServlet:
                enabled: true
                # 设置白名单，不填则允许所有访问
                allow:
                url-pattern: /druid/*
                # 控制台管理用户名和密码
                login-username: ruoyi
                login-password: 123456
            filter:
                stat:
                    enabled: true
                    # 慢SQL记录
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true

